# Generated by Django 5.0 on 2026-03-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workspace_devices_workspace_invite_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
