# Generated by Django 5.0 on 2026-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='layout_area_m2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='layout_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='layout_polygon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
