# Generated by Django 5.0 on 2026-03-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspace_layout_area_m2_workspace_layout_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='layout_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='layout_job_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='layout_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
