# Generated by Django 5.0 on 2026-03-06 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260306_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_id', models.CharField(db_index=True, max_length=100)),
                ('incident_type', models.CharField(db_index=True, max_length=60)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=220)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.workspace')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('workspace', 'gateway_id', 'incident_type'), name='uniq_open_incident_per_type'),
        ),
    ]
